### PR TITLE
update hardening to current version

### PR DESCRIPTION
**Pull request by Meecr0b**
What this PR does / why we need it:

Update devsec -hardening to current version

### CODE REVIEW

**Comment by Meecr0b** [comment]
# changes:

## Overview:

- auditd: make hardcoded settings manageable (keep default values)
- ansible dependency updated to ~~2.9.10~~ -> 2.11
- a lot of linting improvements and implementation of best practices 
  - Use of ansible fqdn module names (~`include_vars:`~ -> `ansible.builtin.include_vars)`
- ssh hardening: Add support for OpenBSD


## Details:

### Default variables

```diff
+# Set to `false` to disable "chmod 700" of home folders for regular users
+os_chmod_rootuser_home_folder: true

+# Specify user accounts, whose home folders shouldn't be chmodded to 700 when "os_chmod_home_folders" is enabled.
-os_ignore_home_folder_users: ['lost+found']
+os_ignore_home_folder_users: []

+# Set to false to disable password age enforcement on existing users
+os_rootuser_pw_ageing: false

+# When enabled and there are multiple users with UID=0, only "root" will be kept. Others will be deleted.
+os_remove_additional_root_users: false

+# Set to false to disable password age enforcement on existing users
+os_user_pw_ageing: true

+# List of users, where password ageing should not be enforced even if "os_user_pw_ageing" is enabled
+os_users_without_password_ageing: []

+net.ipv6.conf.all.router_solicitations: 0
+net.ipv6.conf.all.autoconf: 0
```
### important for us

- new variable `os_user_pw_ageing`, where we can disable passwort aging

**Comment by seanschneeweiss** [comment]
Can we run e2e test on an image build with this update? Or will we test this as part of another PR, e.g. when using the new image in [t1/configuration.go](https://git.i.mercedes-benz.com/c445/t1/blob/90a0b04a5f261a4e6eb8539f375cf6c271ea0c4a/caas/go/pkg/services/kubeadm/configuration.go#L65-L68).

**Comment by Meecr0b** [comment]
# diff from ansible

## /etc/audit/auditd.conf

Just comments will be removed, also auditd.conf will be overwritten by cloudinit

```diff
--- before: /etc/audit/auditd.conf
+++ after: /.ansible/tmp/auditd.conf.j2
@@ -13,7 +13,6 @@
 disp_qos = lossy
 dispatcher = /sbin/audispd
 name_format = NONE
-##name = mydomain
 max_log_file = 6
 max_log_file_action = keep_logs
 space_left = 75
@@ -23,11 +22,8 @@
 admin_space_left_action = SUSPEND
 disk_full_action = SUSPEND
 disk_error_action = SUSPEND
-##tcp_listen_port =
 tcp_listen_queue = 5
 tcp_max_per_addr = 1
-##tcp_client_ports = 1024-65535
 tcp_client_max_idle = 0
 enable_krb5 = no
 krb5_principal = auditd
-##krb5_key_file = /etc/audit/audit.key
```

## mount permission of /var/log

changing group from root to syslog should be OK

```diff
--- before
+++ after
@@ -1,2 +1,2 @@
-group: 0
+group: 110
 path: /var/log
 ```
 
## sysctl settings

We are not using IPv6 at all.
net.ipv6.conf.all.router_solicitations: Number of Router Solicitations to send until assuming no routers are present.

```diff
net.ipv6.conf.all.router_solicitations
- -1
+ 0
net.ipv6.conf.all.autoconf
- 1
+ 0
```

**Comment by Meecr0b** [comment]
> Can we run e2e test on an image build with this update? Or will we test this as part of another PR, e.g. when using the new image in [t1/configuration.go](https://git.i.mercedes-benz.com/c445/t1/blob/90a0b04a5f261a4e6eb8539f375cf6c271ea0c4a/caas/go/pkg/services/kubeadm/configuration.go#L65-L68).

this should be covered in nighlies after we build a new image

**Review by tobiasgiese — APPROVED** [review]

**Review by seanschneeweiss — APPROVED** [review]

**Pull request merged**
